// Project index. `external` entries open off-site, the rest route to a detail page.
const projects = [
  {
    title: 'Synthetic Data',
    href: 'https://github.com/dastanNurbek/unity_augmentation',
    external: true,
    image: '/images/unity-augmentation.png',
    blurb: 'Unity-generated synthetic satellite data for deep learning, applied to a wildfire classification study.',
    tags: ['Unity', 'Deep Learning'],
  },
  {
    title: 'Copurrnicus Game',
    href: 'https://play.unity.com/en/games/6e97a30f-d1dc-494d-a115-77d721f6445c/copernicus',
    external: true,
    image: '/images/copernicus-laptop.png',
    blurb: "Educational game promoting the EU's Copernicus programme and its services.",
    tags: ['Unity', 'Game'],
  },
  {
    title: 'CampusMap Game',
    href: '/campusmap',
    image: '/images/campus-map.png',
    blurb: 'Serious game built to explore Z_GIS and interact with real-time campus data in 3D.',
    tags: ['Unity', 'ArcGIS SDK'],
  },
  {
    title: 'AI for Agriculture',
    href: 'https://github.com/dastanNurbek/beyond-visible-spectrum-submission',
    external: true,
    image: '/images/beyond-spectrum.png',
    blurb: 'Kaggle submission for the ICPR 2026 competition “Beyond Visible Spectrum: AI for Agriculture”, using a custom network architecture.',
    tags: ['PyTorch', 'Competition'],
  },
  {
    title: 'Distributed DL',
    href: '/big-data-dl',
    image: '/images/big-data.png',
    blurb: 'Training a U-Net on BigEarthNet across a Spark cluster.',
    tags: ['PySpark', 'Deep Learning'],
  },
  {
    title: 'Distributed ML',
    href: '/big-data-ml',
    image: '/images/big-data.png',
    blurb: 'Distributed random forest classification of the FRACTAL LiDAR point cloud dataset.',
    tags: ['PySpark', 'MLlib'],
  },
  {
    title: 'Road Extraction',
    href: 'https://github.com/dastanNurbek/torchgeo-road-extraction',
    external: true,
    image: '/images/road-extraction.png',
    blurb: 'An in-depth TorchGeo tutorial for road extraction on the DeepGlobe 2018 challenge dataset.',
    tags: ['TorchGeo', 'Segmentation'],
  },
  {
    title: 'Aircraft Detection',
    href: '/aircraft-detection',
    image: '/images/aircraft-detection.png',
    blurb: 'Object detection in satellite imagery, comparing YOLO against Faster R-CNN.',
    tags: ['YOLO', 'Faster R-CNN'],
  },
  {
    title: 'Dengue AI',
    href: '/dengue-competition',
    image: '/images/dengue.png',
    blurb: 'Predicting future dengue fever outbreaks with a scikit-learn random forest.',
    tags: ['Scikit-learn', 'Forecasting'],
  },
  {
    title: 'Spatial Simulation',
    href: '/traffic-emission-simulation',
    image: '/images/traffic.png',
    blurb: 'Agent-based study of traffic emission impacts on air quality in Paris.',
    tags: ['GAMA', 'Simulation'],
  },
  {
    title: 'Earthquake Displacement',
    href: 'https://earth.google.com/earth/d/1cPCmIYKlfh73nHOM7u8IRuLH059doEWs?usp=sharing',
    external: true,
    image: '/images/displacement.png',
    blurb: 'Displacement map of the 2024 Japan earthquake, produced in SNAP from SAR interferometry.',
    tags: ['SNAP', 'InSAR'],
  },
  {
    title: 'eCognition vs. Open-source',
    href: '/segmentation',
    image: '/images/segmentation.png',
    blurb: 'Benchmarking eCognition against Python segmentation tooling.',
    tags: ['eCognition', 'Python'],
  },
  {
    title: 'Water Area Calculator',
    href: '/sen2cube',
    image: '/images/sen2cube.png',
    blurb: 'Semantic EO data cube model for water area calculation, built on Sen2Cube.at.',
    tags: ['Sen2Cube.at', 'EO Cube'],
  },
  {
    title: 'River Flood Illustration',
    href: 'https://ee-dastannurbek22.projects.earthengine.app/view/ural-river-flood',
    external: true,
    image: '/images/gee-flood.png',
    blurb: 'Slider-widget app illustrating the 2024 Ural River flood.',
    tags: ['Earth Engine', 'Web App'],
  },
  {
    title: 'Wildfire Case Study',
    href: '/eo-browser',
    image: '/images/eo-browser.png',
    blurb: 'Burnt-area assessment in the Abai region, Kazakhstan, using custom scripts in EO Browser.',
    tags: ['EO Browser', 'JavaScript'],
  },
  {
    title: 'Orbit Explorer',
    href: 'https://orbit-explorer.streamlit.app/',
    external: true,
    image: '/images/orbit.png',
    blurb: 'Web app for exploring satellite orbit types and visualising their ground tracks.',
    tags: ['Streamlit', 'Orbital Mechanics'],
  },
  {
    title: 'Image Editor',
    href: 'https://github.com/dastanNurbek',
    external: true,
    image: '/images/editor.png',
    blurb: 'Mobile editor using look-up tables for filters and GLSL fragment shaders to apply them.',
    tags: ['Flutter', 'GLSL'],
  },
];

export default projects;
