// Project index. `external` entries open off-site, the rest route to a detail page.
// Card art is served from /images/cards: 600px WebP, a few tens of KB each.
const projects = [
  {
    title: 'WorldWeaver Fire',
    href: 'https://github.com/dastanNurbek/worldweaver-fire',
    external: true,
    image: '/images/cards/worldweaver-fire.webp',
    blurb: 'A WorldWeaver fork that spreads wildfire across open geodata with a shortest-path flammability model, rendering pre- and post-fire pairs as synthetic training data.',
    tags: ['Blender', 'Python'],
  },
  {
    title: 'Synthetic-6000',
    href: 'https://zenodo.org/records/23117919',
    external: true,
    image: '/images/cards/synthetic-6000.webp',
    blurb: '6,000 procedurally generated pre- and post-fire scene pairs over rural France, with burned-area masks derived from simulated fire spread rather than manual annotation.',
    tags: ['Dataset', 'Zenodo'],
  },
  {
    title: 'Synthetic Data',
    href: 'https://github.com/dastanNurbek/unity_augmentation',
    external: true,
    image: '/images/cards/unity-augmentation.webp',
    blurb: 'Unity-generated synthetic satellite data for deep learning, applied to a wildfire classification study.',
    tags: ['Unity', 'Deep Learning'],
  },
  {
    title: 'CampusMap',
    href: '/campusmap',
    image: '/images/cards/campus-map.webp',
    blurb: '3D digital twin built to explore Z_GIS and interact with real-time campus data.',
    tags: ['Unity', 'ArcGIS SDK'],
  },
  {
    title: 'Copurrnicus Game',
    href: 'https://play.unity.com/en/games/6e97a30f-d1dc-494d-a115-77d721f6445c/copernicus',
    external: true,
    image: '/images/cards/copernicus-laptop.webp',
    blurb: "Educational game promoting the EU's Copernicus programme and its services.",
    tags: ['Unity', 'Game'],
  },
  {
    title: 'AI for Agriculture',
    href: 'https://github.com/dastanNurbek/beyond-visible-spectrum-submission',
    external: true,
    image: '/images/cards/beyond-spectrum.webp',
    blurb: 'Kaggle submission for the ICPR 2026 competition “Beyond Visible Spectrum: AI for Agriculture”, using a custom network architecture.',
    tags: ['PyTorch', 'Competition'],
  },
  {
    title: 'Distributed DL',
    href: '/big-data-dl',
    image: '/images/cards/big-data.webp',
    blurb: 'Training a U-Net on BigEarthNet across a Spark cluster.',
    tags: ['PySpark', 'Deep Learning'],
  },
  {
    title: 'Distributed ML',
    href: '/big-data-ml',
    image: '/images/cards/big-data.webp',
    blurb: 'Distributed random forest classification of the FRACTAL LiDAR point cloud dataset.',
    tags: ['PySpark', 'MLlib'],
  },
  {
    title: 'Road Extraction',
    href: 'https://github.com/dastanNurbek/torchgeo-road-extraction',
    external: true,
    image: '/images/cards/road-extraction.webp',
    blurb: 'An in-depth TorchGeo tutorial for road extraction on the DeepGlobe 2018 challenge dataset.',
    tags: ['TorchGeo', 'Segmentation'],
  },
  {
    title: 'Aircraft Detection',
    href: '/aircraft-detection',
    image: '/images/cards/aircraft-detection.webp',
    blurb: 'Object detection in satellite imagery, comparing YOLO against Faster R-CNN.',
    tags: ['YOLO', 'Faster R-CNN'],
  },
  {
    title: 'Dengue AI',
    href: '/dengue-competition',
    image: '/images/cards/dengue.webp',
    blurb: 'Predicting future dengue fever outbreaks with a scikit-learn random forest.',
    tags: ['Scikit-learn', 'Forecasting'],
  },
  {
    title: 'Spatial Simulation',
    href: '/traffic-emission-simulation',
    image: '/images/cards/traffic.webp',
    blurb: 'Agent-based study of traffic emission impacts on air quality in Paris.',
    tags: ['GAMA', 'Simulation'],
  },
  {
    title: 'Earthquake Displacement',
    href: 'https://earth.google.com/earth/d/1cPCmIYKlfh73nHOM7u8IRuLH059doEWs?usp=sharing',
    external: true,
    image: '/images/cards/displacement.webp',
    blurb: 'Displacement map of the 2024 Japan earthquake, produced in SNAP from SAR interferometry.',
    tags: ['SNAP', 'InSAR'],
  },
  {
    title: 'eCognition vs. Open-source',
    href: '/segmentation',
    image: '/images/cards/segmentation.webp',
    blurb: 'Benchmarking eCognition against Python segmentation tooling.',
    tags: ['eCognition', 'Python'],
  },
  {
    title: 'Water Area Calculator',
    href: '/sen2cube',
    image: '/images/cards/sen2cube.webp',
    blurb: 'Semantic EO data cube model for water area calculation, built on Sen2Cube.at.',
    tags: ['Sen2Cube.at', 'EO Cube'],
  },
  {
    title: 'River Flood Illustration',
    href: 'https://ee-dastannurbek22.projects.earthengine.app/view/ural-river-flood',
    external: true,
    image: '/images/cards/gee-flood.webp',
    blurb: 'Slider-widget app illustrating the 2024 Ural River flood.',
    tags: ['Earth Engine', 'Web App'],
  },
  {
    title: 'Wildfire Case Study',
    href: '/eo-browser',
    image: '/images/cards/eo-browser.webp',
    blurb: 'Burnt-area assessment in the Abai region, Kazakhstan, using custom scripts in EO Browser.',
    tags: ['EO Browser', 'JavaScript'],
  },
  {
    title: 'Orbit Explorer',
    href: 'https://orbit-explorer.streamlit.app/',
    external: true,
    image: '/images/cards/orbit.webp',
    blurb: 'Web app for exploring satellite orbit types and visualising their ground tracks.',
    tags: ['Streamlit', 'Orbital Mechanics'],
  },
  {
    title: 'Image Editor',
    href: 'https://github.com/dastanNurbek',
    external: true,
    image: '/images/cards/editor.webp',
    blurb: 'Mobile editor using look-up tables for filters and GLSL fragment shaders to apply them.',
    tags: ['Flutter', 'GLSL'],
  },
];

export default projects;
